### ISSUE TITLE
Revise spacing For "Buildings for Boinking" Article

### ISSUE THREAD

**Issue by ellepants** [CapitalistLepton/fishwrapper#13]
I can't seem to double the spacing between the bolded sections and the intro, but that would make this guide a lot cleaner

**Comment by CapitalistLepton** [comment]
Closed with [44ed84b186e35dead8a7fec24028a7ea37df9e16](https://github.com/CapitalistLepton/fishwrapper/commit/44ed84b186e35dead8a7fec24028a7ea37df9e16)
